project:
  type: website
  output-dir: docs

website:
  title: "LangFuse Tracing at Justice AI"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Understanding"
        menu:
          - text: "What is Langfuse?"
            file: explanation/overview.qmd
      - text: "Learning"
        menu:
          - text: "Quick Start"
            file: tutorials/quickstart.qmd
          - text: "Basic Python Tracing"
            file: tutorials/basic.qmd
      - text: "Problem Solving"
        menu:
          - text: "LLM Applications"
            file: how-to/llm.qmd
          - text: "Complex Workflows"
            file: how-to/workflow.qmd
          - text: "Azure Deployment"
            file: how-to/azure.qmd
          - text: "Environment Config"
            file: how-to/config.qmd
          - text: "Troubleshooting"
            file: how-to/troubleshooting.qmd
    right:
      - icon: github
        href: https://github.com/JusticeAIUnit/langfuse-tracing-selfhost

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
    code-fold: true
    highlight-style: github
    mermaid:
      theme: neutral

execute:
  freeze: auto 