project:
  type: website
  output-dir: docs

website:
  title: "LangFuse Tracing at Justice AI"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Understanding"
        menu:
          - text: "What is Langfuse?"
            file: explanation/overview.qmd
          - text: "Self-Hosted LangFuse"
            file: explanation/self-hosting.qmd
          - text: "Azure Architecture"
            file: explanation/azure-architecture.qmd
          - text: "Observability Hierarchy"
            file: explanation/observability-hierarchy.qmd
      - text: "Learning"
        menu:
          - text: "Quick Start"
            file: tutorials/quickstart.qmd
          - text: "Basic Python Tracing"
            file: tutorials/basic.qmd
      - text: "Guides"
        menu:
          - text: "─── Application Tracing ───"
          - text: "LangFuse Python SDK"
            file: how-to/python-sdk.qmd
          - text: "OpenTelemetry Library"
            file: how-to/opentelemetry.qmd
          - text: "Python requests Library"
            file: how-to/raw-requests.qmd
          - text: "─── Infrastructure & Deployment ───"
          - text: "Azure Deployment"
            file: how-to/azure-deployment.qmd
          - text: "SSL Certificates"
            file: how-to/ssl-certificates.qmd
          - text: "Email Notifications"
            file: how-to/email-notifications.qmd
          - text: "User Management"
            file: how-to/user-management.qmd
          - text: "Deployment Troubleshooting"
            file: how-to/deployment-troubleshooting.qmd
    right:
      - icon: github
        href: https://github.com/JusticeAIUnit/langfuse-tracing-selfhost

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
    code-fold: true
    highlight-style: github
    mermaid:
      theme: neutral

execute:
  freeze: auto 